# Generated by Django 3.2.12 on 2022-03-24 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartshopperapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='configuration_id',
            new_name='configuration',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='listitem',
            old_name='list_id',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='listitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
