# Generated by Django 3.2.12 on 2022-03-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshopperapp', '0002_auto_20220323_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
