# Generated by Django 3.2.12 on 2022-03-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshopperapp', '0003_alter_list_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(default='Undefined', max_length=50, null=True),
        ),
    ]
