# Generated by Django 3.2.12 on 2022-04-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartshopperapp', '0005_auto_20220413_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryinventory',
            name='grocery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartshopperapp.grocerydetails'),
        ),
    ]
