# Generated by Django 3.2.12 on 2022-04-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshopperapp', '0006_groceryinventory_grocery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, null=True)),
                ('city_address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
