# Generated by Django 3.2.12 on 2022-04-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshopperapp', '0007_citydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryinventory',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='groceryinventory',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
