# Generated by Django 3.2.12 on 2022-04-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshopperapp', '0008_auto_20220418_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryinventory',
            name='cost',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
